version: '3.8'

services:
  ai-companion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-companion
    restart: unless-stopped
    
    # Переменные окружения
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    
    # Монтируем конфигурацию и данные
    volumes:
      - ./config:/home/companion/config:ro
      - ./data:/home/companion/data
      - ./logs:/home/companion/logs
    
    # Сетевые настройки
    networks:
      - companion-network
    
    # Порты (если нужен веб-интерфейс)
    # ports:
    #   - "5000:5000"
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    
    # Проверка здоровья
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  companion-network:
    driver: bridge